In [1]:
#importing numpy to document
import numpy as np

In [2]:
#checking numpy version
print(np.__version__)

1.21.5


In [3]:
#creating numpy array from list
myArr = np.array([1,2,3,4,5])
print(myArr)

[1 2 3 4 5]


In [4]:
#checking data types of numpy array
print(type(myArr))

<class 'numpy.ndarray'>


In [5]:
#creating numpy from tuple
myArr = np.array((1,2,3,4,5))
print(myArr)

[1 2 3 4 5]


# Dimension on Numpy Array

A dimension in arrays is one level of array depth (nested array)

In [6]:
# 0-D Arrays
import numpy as mp
myArr = np.array(10)
print(myArr)

10


In [7]:
#Creating 1-D Arrays
myArr = np.array([1,2,3,4,5])
print(myArr)

[1 2 3 4 5]


In [9]:
#Creating 2-D Arrays
myArr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(myArr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
#Creating 3-D Arrays
myArr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
print(myArr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]


In [11]:
#Check how many dimensions the array
print(myArr.ndim)

3


In [13]:
#Create an arrays with 5 dimensions and verify that it has 5 dimension
myArr = np.array([1,2,3,4], ndmin=5)
print(myArr)

[[[[[1 2 3 4]]]]]


In [14]:
#get the first element from the following array
myArr = np.array([1,2,3,4,5])
print(myArr[0])

1


In [15]:
#get the third and fourth element from the following array
print(myArr[2] + myArr[3])

7


In [16]:
#access array on the first row second column
myArr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(myArr[0,1])

2


In [17]:
#Access the third element of the second array of the first array
myArr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(myArr[0,1,2])

6


In [18]:
#Print the last elementfrom the 2nd dimension
myArr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Last Element from 2nd dim :", myArr[1,-1])

Last Element from 2nd dim : 10


In [19]:
#Slice element from index 1 to index 5 from the following array
myArr = np.array([1,2,3,4,5,6,7,8])
print(myArr[1:5])

[2 3 4 5]


In [20]:
#Slice element from index 4 to the end of array
print(myArr[4:])

[5 6 7 8]


In [21]:
#slice element from the beginning to index 4(not include)
print(myArr[:4])

[1 2 3 4]


In [22]:
#Slice from the index 3 from to the end to index 1 from to the end
print(myArr[-3:-1])

[6 7]


In [23]:
myArr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(myArr[1, 1:4])

[7 8 9]


In [24]:
#From both element, return index 2
print(myArr[0:2, 2])

[3 8]
